Be careful about setting environment variables per platform

diff --git a/docker/Dockerfile.firedrake b/docker/Dockerfile.firedrake
--- a/docker/Dockerfile.firedrake
+++ b/docker/Dockerfile.firedrake
@@ -2,6 +2,15 @@
 
 FROM firedrakeproject/firedrake-vanilla-default:latest
 
+# Architecture specific flags
+ARG X86
+ARG ARM64
+RUN \
+        if [ $(( "${X86:-0}" + "${ARM64:-0}" )) -ne 1 ]; then \
+                echo "Error: must set only one of 'X86' and 'ARM64'" \
+                && exit 1; \
+        fi
+
 # Install optional dependencies
 RUN pip install --verbose \
         --extra-index-url https://download.pytorch.org/whl/cpu \
@@ -10,7 +19,7 @@ RUN pip install --verbose \
 # Install ngsPETSc and dependencies. Netgen do not package ARM wheels so
 # we have to build it from source in that case.
 RUN \
-        if [ "$(dpkg --print-architecture)" == "arm64" ]; then \
+        if [ "${ARM64:-0}" = "1" ]; then \
                 apt-get update \
                 && apt-get -y install python3-tk libxmu-dev tk-dev tcl-dev cmake g++ libglu1-mesa-dev liblapacke-dev libocct-data-exchange-dev libocct-draw-dev occt-misc libtbb-dev libxi-dev \
                 && rm -rf /var/lib/apt/lists/* \
@@ -27,14 +36,10 @@ RUN \
                 pip install ngsPETSc; \
         fi
 
-# Dockerfiles do not allow conditional ENV statements so we have to set
-# things for both the ARM and x86 cases.
-# ARM:
-ENV PATH=/opt/ngsuite/netgen-install/bin:$PATH
-ENV PYTHONPATH=/opt/ngsuite/netgen-install/lib/python3.12/site-packages:$PYTHONPATH
-# x86:
-# (see https://github.com/NGSolve/netgen/issues/213).
-ENV PYTHONPATH=/usr/local/lib/python3.12/site-packages:$PYTHONPATH
+# Set some environment variables.
+# For x86 we have to set PYTHONPATH because of https://github.com/NGSolve/netgen/issues/213.
+ENV PATH=${ARM64:+/opt/ngsuite/netgen-install/bin:}$PATH
+ENV PYTHONPATH=${ARM64:+/opt/ngsuite/netgen-install/lib/python3.12/site-packages:}${X86:+/usr/local/lib/python3.12/site-packages:}$PYTHONPATH
 
 # Install some other niceties
 RUN apt-get update \
