Hacky check for workflow step that I think may not work

diff --git a/.github/workflows/core.yml b/.github/workflows/core.yml
--- a/.github/workflows/core.yml
+++ b/.github/workflows/core.yml
@@ -116,6 +116,18 @@ jobs:
           path: firedrake-repo
           ref: ${{ inputs.source_ref }}
 
+      # UNDO ME, just testing
+      - name: Check version number matches
+        working-directory: firedrake-repo
+        run: |
+          if [ -z $( grep "version = \"${{ inputs.target_branch }}\"" pyproject.toml ) ]; then
+            echo "match not found"
+          else
+            echo "match found"
+          fi
+          : # Stop here
+          exit 1
+
       - name: Validate single source of truth
         run: ./firedrake-repo/scripts/check-config
 
